spring:
  servlet:
    multipart:    # spring mvc文件上传
      max-request-size: 10MB
      max-file-size: 1MB
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://39.104.119.48:1433;DatabaseName=UPS-Single-Window
    username: sa
    password: ENC(vo+Ce07+xRPn8ISP85PR/zRpWbP0slFN)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: GuliHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      connection-test-query: SELECT 1
  # jpa配置
  jpa:
    show-sql: true
    database: sql_server
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

azure:
  storage:
    default-endpoints-protocol: https
    account-name: chetwht
    account-key: ENC(47qpkA/jZZ80BZuBMtPLWsjqzweOJXg/Pp1V93H6O1ybBAfD0Kh0n5fD2hYc2/EbDhImXfcl9Y62kEwL0nY6igyHnjRaXlCEOuTzx8Mi558RPN+5ge7jYr9r5NxFjLBRJadv7SfTM6E=)
    endpoint-suffix: core.windows.net

